### ISSUE TITLE
Missing CRNetworking

### ISSUE THREAD

**Issue by lejacobroy** [crsantos/stravaapiclient-swift#35]
Hi Carlos,

I'm looking into this Strava API swift wrapper, and there seems to be a missing repo, CRNetworking : https://github.com/crsantos/CRNetworking/tree/983e63a922e67bd41b9c757610111bdd15cecc25

As such, I cannot build the project and try to extend its API coverage.

Thank you for your time!

**Comment by crsantos** [comment]
Hi @lejacobroy 

Apologies, I'm not sure why I had that repo as private, it's a simple rest client, a wrapper on top of URLSession.

I have configured as a submodule, but it can be referenced as a podspec depedency if we need.

https://github.com/crsantos/CRNetworking

I have opened it so you can dig in.

⚠️ Disclaimer: I don't touch this codebase for quite a while, so we may need to bump some things, specifically fix warnings on newer Xcode versions, like 14.3.

**Comment by lejacobroy** [comment]
Hi @crsantos ,

This is fantastic, thanks for reviving this repo haha!

I'll dig around and might fork a version to not bother you with PRs on an unmaintained project.

Thank you!
